### ISSUE TITLE
Possible to have examples ?

### ISSUE THREAD

**Issue by throrin19** [kumaravel29/sankey-panel#12]
Hello, it's possible to have diagram examples with datasources usage ? I don't understand how to use it with elastic Search and graphite (if it's possible).

Thanks

**Comment by kumaravel29** [comment]
This plugin is compatible with Elasticsearch only. Sample - https://github.com/kumaravel29/sankey-panel/blob/master/src/img/sankey-panel-query-example.png

The minimum requirement would be to have 2 grouping terms
May be will add more description on the usage.
