### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sanchomuzax** [kumaravel29/sankey-panel#13]
I can't install it.

It's okay:

~~~
git clone https://github.com/kumaravel29/sankey-panel.git
sudo service grafana-server restart
~~~

I inserted this to the `/etc/grafana/grafana.ini` file, and after restart the Grafana server again.

~~~
[plugin.sankey]
path = /home/user.name/sankey-panel
~~~

Where is the Grafana index.html file?

I found an `index.html` file in this folder:

~~~
/usr/share/grafana/public/views
~~~

I try to insert the script to header or before the `/body`, and after restart the Grafana server. But I can't found 'Sankey' in graphs/plugins.

What is the problem? Why can't see it?

Version of the Grafana:  `Grafana v6.2.5`

**Comment by kumaravel29** [comment]
As of now, the plugin is not compatible with Grafana 6

**Comment by sanchomuzax** [comment]
Ok, tnx!
