### ISSUE TITLE
Support for Grafana 5.1.x

### ISSUE THREAD

**Issue by joriws** [kumaravel29/sankey-panel#2]
Thanks for your promising work. I was trying to test this by git cloning to /var/lib/grafana/plugins and adding loader.js to /usr/share/grafana/public/views/index.html to end of file.

On new dashboard I just see Sankey "loaded", displaying "Panel title" and from legends "current". But I cannot edit the dashboard to test it out.

Any help/tips how to fix or are you planning upgrades to later Grafana?

**Comment by joriws** [comment]
![image](https://user-images.githubusercontent.com/5603060/40352399-62d4eaca-5db7-11e8-8f9a-4d656a3be7a5.png)

**Comment by joriws** [comment]
The plugin/panel screen shows:
Dependencies
    Grafana 4.6

**Comment by kumaravel29** [comment]
@joriws i will check and try upgrading it to the version supported for Grafana 5.1.x

**Comment by C-Bam** [comment]
Hey there :) I stil have the same issue :(

**Comment by kumaravel29** [comment]
@joriws and @C-Bam 
I have updated the plugin for supporting in Grafana 5.x
